interface player {
    name: string;
    goals: number;
    shots: number;
    assists: number;
    errors: number;
    twoMin: number;
    yellowCard: number;
    scoringPercentage: number;
    freeThrows: number;
    penalty: number;
    burnedPenalty: number;
}

const players: Array<player> = [
  {
    name: 'Magnus Jacobsen',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
  {
    name: 'Rasmus Kirt',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
  {
    name: 'Jeppe Dreier',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
  {
    name: 'Nikolaj Brinkmann',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
  {
    name: 'Nikolaj Damkjær',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
  {
    name: 'Jesper Ravn',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
  {
    name: 'Magnus Linnebjerg',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
  {
    name: 'Klaus Andersen',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
  {
    name: 'Julius Thomsen',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
  {
    name: 'Sune jørgensen',
    goals: 0,
    shots: 0,
    assists: 0,
    errors: 0,
    twoMin: 0,
    yellowCard: 0,
    scoringPercentage: 0,
    freeThrows: 0,
    penalty: 0,
    burnedPenalty: 0,
  },
]

export default players;